---
APPLY_FIXES: all
DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
# ENABLE_LINTERS:
#   - MARKDOWN_MARKDOWNLINT
ENABLE:
  - MARKDOWN
  - SPELL
FILTER_REGEX_INCLUDE: (_posts/)
FLAVOR: ruby
FLAVOR_SUGGESTIONS: false
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
