---
APPLY_FIXES: all
# DISABLE_LINTERS:
#   - MARKDOWN_MARKDOWN_LINK_CHECK
# ENABLE_LINTERS:
#   - MARKDOWN_MARKDOWNLINT
ENABLE:
  - MARKDOWN
  - SPELL
  - JAVASCRIPT
MARKDOWN_FILTER_REGEX_INCLUDE: (_posts/)
JAVASCRIPT_FILTER_REGEX_INCLUDE: (custom_lint_rules)
JAVASCRIPT_FILTER_REGEX_EXCLUDE: (_site/)
SPELL_FILTER_REGEX_INCLUDE: (_posts/)
FLAVOR: ruby
FLAVOR_SUGGESTIONS: false
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
JAVASCRIPT_DEFAULT_STYLE: prettier