---
APPLY_FIXES: all
# DISABLE_LINTERS:
#   - MARKDOWN_MARKDOWN_LINK_CHECK
ENABLE:
  - MARKDOWN
  - SPELL
  - JAVASCRIPT
JAVASCRIPT_FILTER_REGEX_INCLUDE: (custom_lint_rules|js)
FILTER_REGEX_EXCLUDE: (_site/|test_posts/)
MARKDOWN_FILTER_REGEX_INCLUDE: (_posts/)
SPELL_FILTER_REGEX_INCLUDE: (_posts/)
FLAVOR: ruby
FLAVOR_SUGGESTIONS: false
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
JAVASCRIPT_DEFAULT_STYLE: prettier
MARKDOWN_MARKDOWNLINT_ARGUMENTS: -r "/tmp/lint/custom_lint_rules"